### ISSUE TITLE
MySQL-Python will fail in docker-opensource, cannot find mysql-config

### ISSUE THREAD

**Issue by Aegeaner** [Yelp/mysql_streamer#12]
```
Downloading/unpacking MySQL-python==1.2.5 (from -r /Users/User/Code/mysql_streamer/requirements-opensource.txt (line 4))
  Downloading MySQL-python-1.2.5.zip (108kB): 108kB downloaded
  Running setup.py (path:/Users/MOMO/Code/mysql_streamer/venv/py27/build/MySQL-python/setup.py) egg_info for package MySQL-python
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/User/Code/mysql_streamer/venv/py27/build/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/User/Code/mysql_streamer/venv/py27/build/MySQL-python/setup.py", line 17, in <module>

    metadata, options = get_config()

  File "setup_posix.py", line 43, in get_config

    libs = mysql_config("libs_r")

  File "setup_posix.py", line 25, in mysql_config

    raise EnvironmentError("%s not found" % (mysql_config.path,))

EnvironmentError: mysql_config not found
```

**Comment by lsterk** [comment]
Thanks for filing the issue - we aren't maintaining this repository any longer, but thanks for checking it out!
