### ISSUE TITLE
meet errors when running 'make -f Makefile-opensource test' command

### ISSUE THREAD

**Issue by lynch0227** [Yelp/mysql_streamer#17]
Hi guys,

  when running the 'make -f Makefile-opensource test' command, I get the below errors:
2017-02-03 16:39:08,079 - replication_handler.batch.base_parse_replication_stream:115: ERROR    Shutting down because of exception
Traceback (most recent call last):
  File "/root/mysql_streamer-master/replication_handler/batch/base_parse_replication_stream.py", line 108, in run
    self.process_event(replication_handler_event)
  File "/root/mysql_streamer-master/replication_handler/batch/base_parse_replication_stream.py", line 140, in process_event
    self.current_event_type = self.handler_map[event_class].event_type
KeyError: <class 'mock.mock.MagicMock'>

I find that the reason is because the 'handler_map' function dosen't handle the class MagicMock event type in base_parse_replication_stream.py, could someone can fix it? 
<MagicMock name=u'ReplicationStreamRestarter().get_stream().next().event' id='140589236637520'>

And now we don't have docker environment, can I deploy it in linux environment directly?
Do you have some detail deployment document? Please share it.

Thank you.

**Comment by lsterk** [comment]
Thanks for filing the issue - we aren't maintaining this repository any longer, but thanks for checking it out!
